/* USER CODE BEGIN Header */
/**
  ******************************************************************************
  * @file           : main.c
  * @brief          : Raw BME280 I2C readout
  ******************************************************************************
  */
/* USER CODE END Header */
#include "main.h"
#include "i2c.h"
#include "usart.h"
#include "gpio.h"
#include <stdio.h>

extern I2C_HandleTypeDef hi2c1;
extern UART_HandleTypeDef huart2;

#define BME280_ADDR_76 (0x76 << 1)
#define BME280_ADDR_77 (0x77 << 1)

HAL_StatusTypeDef bme_read(uint16_t devAddr, uint8_t reg, uint8_t *data, uint16_t len) {
  return HAL_I2C_Mem_Read(&hi2c1, devAddr, reg, I2C_MEMADD_SIZE_8BIT, data, len, 100);
}

HAL_StatusTypeDef bme_write(uint16_t devAddr, uint8_t reg, uint8_t val) {
  return HAL_I2C_Mem_Write(&hi2c1, devAddr, reg, I2C_MEMADD_SIZE_8BIT, &val, 1, 100);
}

int __io_putchar(int ch) {
  HAL_UART_Transmit(&huart2, (uint8_t*)&ch, 1, HAL_MAX_DELAY);
  return ch;
}

void SystemClock_Config(void);

int main(void)
{
  HAL_Init();
  SystemClock_Config();
  MX_GPIO_Init();
  MX_I2C1_Init();
  MX_USART2_UART_Init();

  printf("\r\n=== BME280 RAW TEST ===\r\n");

  uint16_t addr = 0;
  if (HAL_I2C_IsDeviceReady(&hi2c1, BME280_ADDR_77, 2, 50) == HAL_OK)
      addr = BME280_ADDR_77;
  else if (HAL_I2C_IsDeviceReady(&hi2c1, BME280_ADDR_76, 2, 50) == HAL_OK)
      addr = BME280_ADDR_76;

  if (!addr) {
    printf("No BME280 found at 0x76 or 0x77.\r\n");
    while (1);
  }

  uint8_t id = 0;
  bme_read(addr, 0xD0, &id, 1);
  printf("Detected device at 0x%02X, ID=0x%02X\r\n", addr>>1, id);

  // Config: normal mode, oversampling x1
  bme_write(addr, 0xE0, 0xB6); // reset
  HAL_Delay(5);
  bme_write(addr, 0xF2, 0x01); // ctrl_hum
  bme_write(addr, 0xF4, 0x27); // ctrl_meas: osrs_t=x1, osrs_p=x1, mode=normal
  bme_write(addr, 0xF5, 0x00); // config

  uint8_t data[8];
  while (1) {
    if (bme_read(addr, 0xF7, data, 8) == HAL_OK) {
      uint32_t adc_P = ((uint32_t)data[0]<<12)|((uint32_t)data[1]<<4)|(data[2]>>4);
      uint32_t adc_T = ((uint32_t)data[3]<<12)|((uint32_t)data[4]<<4)|(data[5]>>4);
      uint32_t adc_H = ((uint32_t)data[6]<<8)|data[7];

      printf("Raw: P=%lu, T=%lu, H=%lu\r\n",
             (unsigned long)adc_P,
             (unsigned long)adc_T,
             (unsigned long)adc_H);
    }
    HAL_Delay(1000);
  }
}

/* SystemClock_Config generated by CubeMX */
void SystemClock_Config(void)
{
  RCC_OscInitTypeDef RCC_OscInitStruct = {0};
  RCC_ClkInitTypeDef RCC_ClkInitStruct = {0};

  HAL_PWREx_ControlVoltageScaling(PWR_REGULATOR_VOLTAGE_SCALE1);

  RCC_OscInitStruct.OscillatorType = RCC_OSCILLATORTYPE_HSI;
  RCC_OscInitStruct.HSIState = RCC_HSI_ON;
  RCC_OscInitStruct.PLL.PLLState = RCC_PLL_ON;
  RCC_OscInitStruct.PLL.PLLSource = RCC_PLLSOURCE_HSI;
  RCC_OscInitStruct.PLL.PLLM = 1;
  RCC_OscInitStruct.PLL.PLLN = 10;
  RCC_OscInitStruct.PLL.PLLP = RCC_PLLP_DIV7;
  RCC_OscInitStruct.PLL.PLLQ = RCC_PLLQ_DIV2;
  RCC_OscInitStruct.PLL.PLLR = RCC_PLLR_DIV2;
  HAL_RCC_OscConfig(&RCC_OscInitStruct);

  RCC_ClkInitStruct.ClockType = RCC_CLOCKTYPE_HCLK|RCC_CLOCKTYPE_SYSCLK|
                                RCC_CLOCKTYPE_PCLK1|RCC_CLOCKTYPE_PCLK2;
  RCC_ClkInitStruct.SYSCLKSource = RCC_SYSCLKSOURCE_PLLCLK;
  RCC_ClkInitStruct.AHBCLKDivider = RCC_SYSCLK_DIV1;
  RCC_ClkInitStruct.APB1CLKDivider = RCC_HCLK_DIV1;
  RCC_ClkInitStruct.APB2CLKDivider = RCC_HCLK_DIV1;
  HAL_RCC_ClockConfig(&RCC_ClkInitStruct, FLASH_LATENCY_4);
}
void Error_Handler(void)
{
  __disable_irq();
  while (1)
  {
    // Optional: blink LED2 to show an error
    // HAL_GPIO_TogglePin(GPIOA, GPIO_PIN_5);
    // HAL_Delay(200);
  }
}
